#!/bin/bash
src="$HOME/Wallpapers"
tar="/usr/share/hypr"
cfg="$HOME/.config/Himapaper.conf"
vim $cfg
for i in 0 1 2; do
  sudo rm $tar/wall$i.png
  sudo ln -s $src/$(head -$(($i + 1)) $cfg | tail -1) $tar/wall$i.png
done
