#!/bin/bash
src="$HOME/Wallpapers"
tar="/usr/share/hypr"
cfg="$HOME/.config/Himapaper.conf"
nm=$(cat $cfg | wc -w)
random=$(od -vAn -N2 -tu2 < /dev/urandom)
echo $random >> ~/rd
rd=$((random % nm))
for i in 0 1 2; do
    sudo rm $tar/wall$i.png
    sudo ln -s $src/$(head -$(($rd + 1)) $cfg | tail -1) $tar/wall$i.png
done
